sudo: false

language: ruby
rvm:
  - 2.3.1

before_install: gem install bundler -v 1.13.6

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - john+apply@carney.id.au
    on_failure: change
    on_success: never
